# build.yaml

targets:
  $default:
    builders:
      graphql_codegen:
        options:
          query : true
          trace : true
          clients:
            - graphql
          outputDirectory : ../../infrastracture/graphQlService/generated
          generatedFileHeader : "// ignore_for_file: camel_case_types ,prefer_is_not_operator, annotate_overrides, prefer_final_fields, non_constant_identifier_names, no_leading_underscores_for_local_identifiers, unnecessary_this, prefer_const_constructors, constant_identifier_names, camel_case_extensions"
          